#!/usr/bin/env python
# Robert Patton, rpatton@fredhutch.org (Ha Lab)
# v1.0, 11/04/2021

# combine _PhasingFM.tsv files generated by GenerateFFTFeatures.py into a single file and remove intermediate files

import argparse
import pandas as pd


def main():
    # parse command line arguments:
    parser = argparse.ArgumentParser(description='\n### CombinePhasingFM.py ### Combine _PhasingFM.tsv files '
                                                 'generated by GenerateFFTFeatures.py into a single file, and '
                                                 'remove the intermediate files')
    parser.add_argument('-i', '--inputs', help='_PhasingFM.tsv files', nargs='*', required=True)
    parser.add_argument('-r', '--results_dir', help='directory for results', required=True)
    args = parser.parse_args()

    df_list = []

    for filename in args.inputs:
        df = pd.read_table(filename, sep='\t', index_col=0)
        df_list.append(df)

    df = pd.concat(df_list, axis=0, ignore_index=False)
    df.to_csv(args.results_dir + '/PhasingFM.tsv', sep='\t')


if __name__ == "__main__":
    main()
